### ISSUE TITLE
Tags with counter on hover

### ISSUE THREAD

**Issue by zaiste** [polyconf/17.polyconf.com#24]
It'd be better to have tags on white/light grey with a left bar in colour e.g.

![screen shot 2017-02-09 at 22 50 11](https://cloud.githubusercontent.com/assets/200613/23228857/5c8f45d6-f93e-11e6-9587-625a45424d8e.png)

when on hover they should be filled with coulor and the counter should be added

![screen shot 2017-02-09 at 21 32 08](https://cloud.githubusercontent.com/assets/200613/23228866/6aadebae-f93e-11e6-95da-2eefb7514f69.png)

**Comment by pieecia** [comment]
ok, got it, one question, can we stay with skills limit up to 3 max 4 in row or I have to expect more?

**Comment by zaiste** [comment]
@morrise yes, good suggestions, let's fix it to 3-4 topics!

**Comment by pieecia** [comment]
@zaiste I just changed tags background to white and added left border. I mentioned on slack that currently on speaker hover is social overlay (blue background on thumbnail) and I couldn't add next hover for counter, so counter are visible at start.

Please check attached screenshot

<img width="1680" alt="zrzut ekranu 2017-02-26 o 21 11 17" src="https://cloud.githubusercontent.com/assets/8327453/23343222/4b3cc3a8-fc68-11e6-9276-cb00133c9f17.png">
